### PR TITLE
Update webpack.md to clarify what the config does

### PR DESCRIPTION
**Pull request by wyuenho**
Remove `cheerio` as it's no longer optional depending on React version. I've also added an alternative config using the IgnorePlugin that will achieve the same effect.

### CODE REVIEW

**Comment by nfcampos** [comment]
Looks great @wyuenho would you mind rebasing on latest master?

**Comment by ljharb** [comment]
@wyuenho any chance you'd be willing to reopen this and rebase it? I'd love to merge it.

**Comment by wyuenho** [comment]
Let me confirm with the people on #47 first. I see people are still using `externals` and I'm not sure why. It can probably be completely done away with.

**Comment by hpurmann** [comment]
I just had a problem with `shallow` when testing with Karma+Webpack (in mocha or when using `mount`, it's fine):
```
TypeError: (0 , _cheerio2.default) is not a function
    at ShallowTestWrapper.get (test/webpack-client-tests.js:69435:44)
    at ShallowTestWrapper.attr (test/webpack-client-tests.js:69351:19)
    at Assertion.<anonymous> (test/webpack-client-tests.js:56696:37)
    at Assertion.<anonymous> (test/webpack-client-tests.js:57115:20)
    at Assertion.ctx.(anonymous function) [as attr] (test/webpack-client-tests.js:11282:34)
    at Context.<anonymous> (test/webpack-client-tests.js:307560:32)
```
Using React 15.4.2 and enzyme 2.6.0.
The problem disappears when removing `cheerio` from externals.

**Pull request closed without merging**
