### PR TITLE
Support portals

### PR DESCRIPTION
**Pull request by louisscruz**
This PR adds support for portals.

In making this PR, I followed the `CONTRIBUTING.md` as closely as possible. This PR essentially adds a test to the [PR](https://github.com/airbnb/enzyme/pull/1263) submitted by @jquense, who should be given credit if this PR is accepted.

I'm not too familiar with the organization of the tests, so you might wish to place the test in a different location. However, it should get the job done.

### CODE REVIEW

**Comment by ljharb** [comment]
Thanks. I'd prefer, in the future, if you posted a link to your commit on the original PR, and I can add it there - opening up a new, duplicate PR clutters the repo.

**Comment by louisscruz** [comment]
Got it, will do.

Louis

**Comment by louisscruz** [comment]
Any chance I can get a review?

**Comment by ljharb** [comment]
I've made this PR, and #1263, have the same contents, and split up your changes into a separate commit.

**Comment by louisscruz** [comment]
Thanks a ton! Feel free to close this out.

**Pull request merged**
