### PR TITLE
add options arg to API docs for debug()

### PR DESCRIPTION
**Pull request by finnigantime**

### CODE REVIEW

**Comment by finnigantime** [comment]
@ljharb Looks to me like mount API docs already show options:
screen shot 2018-01-29 at 2 13 14 pm

**Comment by ljharb** [comment]
@finnigantime that's on `mount` itself; i mean on ReactWrapper's `.debug` method.

**Comment by ljharb** [comment]
I took care of the rebase and the mount docs for you.

**Comment by finnigantime** [comment]
Ah, I was confused what you meant but now all makes sense. Thanks!

**Pull request merged**
