### PR TITLE
Switch to lodash

### PR DESCRIPTION
**Pull request by existentialism**

### CODE REVIEW

**Comment by lelandrichardson** [comment]
@ljharb any issues you can think of with the changes of `object.values` and `object.assign`?

**Comment by ljharb** [comment]
Yes, we shouldn't be using lodash when we don't have to be. @existentialism please only convert existing underscore uses to lodash.

**Comment by existentialism** [comment]
@ljharb @lelandrichardson reverted those changes!

**Comment by lelandrichardson** [comment]
Cool. LGTM!

**Pull request merged**
