### PR TITLE
include only necessary files in npm package

### PR DESCRIPTION
**Pull request by deepsweet**
```
$ tree node_modules/enzyme -I node_modules -L 2

node_modules/enzyme
├── .idea/
│   ├── dictionaries/
│   ├── inspectionProfiles/
│   ├── jsLinters/
│   ├── libraries/
│   ├── .name
│   ├── compiler.xml
│   ├── enzyme.iml
│   ├── jsLibraryMappings.xml
│   ├── misc.xml
│   ├── modules.xml
│   ├── vcs.xml
│   └── workspace.xml
├── build/
│   ├── Debug.js
│   ├── MountedTraversal.js
│   ├── ReactWrapper.js
│   ├── ReactWrapperComponent.js
│   ├── ShallowTraversal.js
│   ├── ShallowWrapper.js
│   ├── Utils.js
│   ├── index.js
│   ├── react-compat.js
│   └── version.js
├── coverage/
│   ├── enzyme/
│   ├── base.css
│   ├── coverage.json
│   ├── coverage.raw.json
│   ├── index.html
│   ├── prettify.css
│   ├── prettify.js
│   ├── sort-arrow-sprite.png
│   └── sorter.js
├── docs/
│   ├── api/
│   ├── guides/
│   ├── installation/
│   ├── GLOSSARY.md
│   ├── README.md
│   ├── future.md
│   └── guides.md
├── src/
│   ├── Debug.js
│   ├── MountedTraversal.js
│   ├── ReactWrapper.js
│   ├── ReactWrapperComponent.jsx
│   ├── ShallowTraversal.js
│   ├── ShallowWrapper.js
│   ├── Utils.js
│   ├── index.js
│   ├── react-compat.js
│   └── version.js
├── test/
│   ├── .eslintrc
│   ├── Debug-spec.js
│   ├── ReactWrapper-spec.js
│   ├── ShallowTraversal-spec.js
│   ├── ShallowWrapper-spec.js
│   ├── Utils-spec.js
│   └── _helpers.js
├── .babelrc
├── .eslintrc
├── .npmignore
├── .travis.yml
├── CHANGELOG.md
├── CONTRIBUTING.md
├── LICENSE.md
├── README.md
├── book.json
├── example-test.sh
├── install-relevant-react.sh
├── package.json
└── withDom.js
```

Loading unnecessary files is one of the reasons `npm install`s take so darn long. Anton Rudeshko very well put it in [his article](http://www.rudeshko.com/web/2014/05/13/help-people-consume-your-npm-packages.html):

> Speaking in terms of object-oriented design, your npm package should be [highly cohesive](https://en.wikipedia.org/wiki/Cohesion_(computer_science)) and [loosely coupled](https://en.wikipedia.org/wiki/Loose_coupling). Your package should do only one thing and do it well.

Corey Butler also wrote [a nice article](https://medium.com/@goldglovecb/npm-needs-a-personal-trainer-537e0f8859c6) about why it's important to minimize module footprints, including test suite:

> In the rare situation a developer actually wants to run your test suite on their own local computer, they'll likely clone or fork it.

Also see [NPM docs](https://docs.npmjs.com/files/package.json#files) for details about `files` field in `package.json`.

### CODE REVIEW

**Comment by deepsweet** [comment]
```
$ cd node_modules/enzyme/
$ du -sh .idea/ coverage/ src/ docs/ test/

88K .idea/
512K coverage/
92K src/
424K docs/
136K test/
```

**Comment by ljharb** [comment]
All files are necessary, as I explained in https://github.com/substack/tape/pull/260. 

All `npm` modules should include every file unless there's a special reason not to.

**Comment by deepsweet** [comment]
even weird `.idea/` and `coverage/` with html report? please EXPLAIN why do I need to download these files on every `npm install`.

**Comment by ljharb** [comment]
I can see most of the gitignored things being npmignored. However, a whitelist in package.json is *very very dangerous* because it's easy to add new files to a package, and forget to add them to a whitelist.

A blacklist approach is the best one - if you'd like to open a PR that copies over many of the gitignore entries to npmignore, that would be fine.

**Comment by deepsweet** [comment]
then please solve my problem the way you like: I don't want to download 1 MB of junk on every `npm install`.

> 48,752 downloads in the last month

https://www.npmjs.com/package/enzyme

**Comment by ljharb** [comment]
I updated the `npmignore` file in d8e4262 to filter out a few more things.

You have a local npm install cache - you only have to download it once per version.

**Comment by deepsweet** [comment]
my own local npm cache is not a solution of this problem. please do not publish `docs/` dir as well, you have gitbook for this.

**Comment by ljharb** [comment]
It is useful to have docs inside `npm explore enzyme`. People do not always have an internet connection available when they want to learn how a package works.

**Pull request closed without merging**
