### PR TITLE
Update Webpack guide for React 15.5

### PR DESCRIPTION
**Pull request by ericgio**
I was having trouble configuring my setup correctly for Webpack + React 15.5 based on the current guide. This PR adds documentation for those using React 15.5+, where `react/addons` is gone and `react-addons-test-utils` is deprecated in favor of `react-test-renderer`.

### CODE REVIEW

**Comment by ericgio** [comment]
Note that Enzyme still raises errors about missing `react/addons` and `react-addons-test-utils` but tests will run. I've opened a [separate issue](https://github.com/airbnb/enzyme/issues/1061) for this.

**Comment by naganowl** [comment]
https://github.com/airbnb/enzyme/pull/1031 is relevant to this as well.

**Comment by ericgio** [comment]
As noted in #1061, I was able to silence the errors by adding the following to `externals`:

```
'react/addons': 'react',
'react-addons-test-utils': 'react-dom',
```

I'm hesitant to add this to the docs, however, since the errors seem like a bug and these lines shouldn't be necessary.

**Comment by ljharb** [comment]
I don't think this is relevant any more now that we're on v3.

**Pull request closed without merging**
