### PR TITLE
Shallow docs: props, prop and key can be called on non-root nodes

### PR DESCRIPTION
**Pull request by mwilliamson**

### CODE REVIEW

**Comment by Aweary** [comment]
Thanks @mwilliamson! would you mind making a couple more changes as well?

  - [ ] Update the doc comment block for `prop`: [ShallowWrapper.js#L616](https://github.com/airbnb/enzyme/blob/master/src/ShallowWrapper.js#L616)

  - [ ] Update the doc comment block for `props`: [ShallowWrapper.js#L491](https://github.com/airbnb/enzyme/blob/master/src/ShallowWrapper.js#L491)


These aren't necessarily part of your current changes, but I noticed they're wrong so if you could fix them so they match the current docs I'd really appreciate it.

  - [ ] Fix the doc comment block for `type` (current node, not root): [ShallowWrapper.js#L635](https://github.com/airbnb/enzyme/blob/master/src/ShallowWrapper.js#L635)

  - [ ] Fix the doc comment block for `name` (current node, not root): [ShallowWrapper.js#L645](https://github.com/airbnb/enzyme/blob/master/src/ShallowWrapper.js#L645).

**Comment by mwilliamson** [comment]
Sure, done. I did the same for `hasClass`, since I believe that can also be called on non-root nodes.

**Comment by Aweary** [comment]
Thanks @mwilliamson, can you fix the linting error being throw in Travis as well?

>
/home/travis/build/airbnb/enzyme/src/ShallowWrapper.js
  635:1  error  Line 635 exceeds the maximum line length of 100  max-len

**Comment by mwilliamson** [comment]
Sure, done.

**Comment by Aweary** [comment]
Thanks @mwilliamson LGTM

**Comment by mwilliamson** [comment]
Thanks!

**Pull request merged**
