### PR TITLE
Tweak the describeWithDOM label

### PR DESCRIPTION
**Pull request by silvenon**
Before:

screenshot 2015-12-05 00 19 44

After:

screenshot 2015-12-05 00 18 49

### CODE REVIEW

**Comment by silvenon** [comment]
Damn, should've skipped the CI.

Let me know if you'd prefer square brackets instead.

**Comment by lelandrichardson** [comment]
@silvenon I'm not particularly attached to one version or another... but was there something that necessitated this change for you or did you just not like the aesthetic of `<< >>`?

**Comment by silvenon** [comment]
* aesthetics :grin:
* readability—message at the bottom is hard to read with `<< >>` because it visually conflicts with tag marks, and `<< >>` takes up way too much space, especially in monospace fonts (typographically `« »` would make more sense, but it doesn't look good either)
* semantics—AFAIK `<< >>` doesn't mean anything, while parenthesis suggest additional info

**Comment by lelandrichardson** [comment]
I don't have any problem with changing it...

@ljharb @goatslacker thoughts?

**Comment by ljharb** [comment]
LGTM - it's just informational logging, so it's barely even a patch-level change :-)

**Comment by lelandrichardson** [comment]
OK. Since I think @silvenon's points have merit, i'm going to go ahead and merge this.

**Comment by silvenon** [comment]
Thanks!

**Pull request merged**
