### PR TITLE
[Docs] Fix alphabetical order of API lists

### PR DESCRIPTION
**Pull request by koba04**
I suppose these API lists are sorting as alphabetical order, aren't they?
This PR is to fix the order.

BTW, Is the following list sorting as some intentional order?

http://airbnb.io/enzyme/docs/api/shallow.html#shallowwrapper-api

Thanks.

### CODE REVIEW

**Comment by ljharb** [comment]
I don't think either list is intended to be sorted in any particular order. I don't mind alphabetizing it, but I also don't think it matters - people will use "find in page" to find something specific, or will browse through them all.

**Comment by koba04** [comment]
I think [ShallowWrapper API](http://airbnb.io/enzyme/docs/api/shallow.html#shallowwrapper-api) looks good to me.

But [Table of Contents](https://github.com/airbnb/enzyme/blob/master/docs/README.md) is cofusing because it's almost alphabetical order, and it's not same as [ShallowWrapper API](http://airbnb.io/enzyme/docs/api/shallow.html#shallowwrapper-api).
(ex. `is(selector)` and `isEmpty()` are not adjacent)

When I write tests with enzyme, I look for a suitable API in the API list of Table of Contents.
I think it would be nice if the list is sorted as some rule.

**Comment by blainekasten** [comment]
I am 👍 for alphabetical lists.

**Comment by blainekasten** [comment]
can you rebase this over master so we can merge it?

**Comment by koba04** [comment]
@blainekasten Thank you! Rebased!

**Comment by blainekasten** [comment]
Thank you @koba04 !

**Comment by koba04** [comment]
Thanks!

**Pull request merged**
