### PR TITLE
[Refactor] Use RSTTraversal childrenOfNode in Utils

### LINKED ISSUE #1380: Different methods for retrieving children from nodes
The [`containsChildrenSubArray`](https://github.com/airbnb/enzyme/blob/master/packages/enzyme/src/Utils.js#L138) method gets the children from the props of the node. Most other methods use the [`childrenOfNode`](https://github.com/airbnb/enzyme/blob/master/packages/enzyme/src/RSTTraversal.js#L11) function that uses the node.rendered property to retrieve children.

Enzyme should only have one method to retrieve children from a node

I've opened a PR that makes the method exported in RSTTraversal the only childrenOfNode method used https://github.com/airbnb/enzyme/pull/1381

### PR DESCRIPTION
**Pull request by eddyerburgh**
Use RSTTraversal childrenOfNode method in Utils

Closes #1380

### CODE REVIEW

**Comment by ljharb** [comment]
Could you please rebase this on the command line, so as to remove all merge commits?

**Comment by eddyerburgh** [comment]
Done 😀

**Comment by eddyerburgh** [comment]
@ljharb when will this be released?

**Comment by ljharb** [comment]
enzyme v3.3.0 is now released.

**Pull request merged**
