### PR TITLE
Add docs for getElement() and getElements()

### PR DESCRIPTION
**Pull request by artiebits**
Issue https://github.com/airbnb/enzyme/issues/1315

### CODE REVIEW

**Comment by artiebits** [comment]
Thanks!

**Comment by bailer** [comment]
Is the new version of the docs not released? I see getElement in this repo but not on the documentation website http://airbnb.io/enzyme/docs/api/shallow.html#getnode--reactelement

**Comment by ljharb** [comment]
Docs are released along with enzyme itself; these haven’t been published yet.

**Comment by smoholkar** [comment]
@ljharb while updating to latest enzyme, I replaced  `.nodes[0].value`  to `.getElements()[0].value` . 
But it's undefined . How do I get the value ? when I log out .getElements()[0] I do see value in the wrapper.

**Comment by ljharb** [comment]
@smoholkar avoid using `[]`, try `.eq(0)` or `.at(0)`?

**Comment by smoholkar** [comment]
@ljharb I still get undefined.  `const inputElement = component.find('input').at(0).value` . My component is mounted & not shallow rendered. Would that matter ?

**Comment by ljharb** [comment]
Can you file a separate issue to keep discussing this? :-)

**Comment by ljharb** [comment]
Bracket access isn’t as explicit; your code will Ben more readable without it.

**Comment by ljharb** [comment]
The following packages are now released:
 - [enzyme v3.4.0](https://www.npmjs.com/package/enzyme)
 - [enzyme-adapter-react-16 v1.2.0](https://www.npmjs.com/package/enzyme-adapter-react-16)
 - [enzyme-adapter-react-16.3 v1.0.0](https://www.npmjs.com/package/enzyme-adapter-react-16.3)
 - [enzyme-adapter-react-16.2 v1.0.0](https://www.npmjs.com/package/enzyme-adapter-react-16.2)
 - [enzyme-adapter-react-16.1 v1.0.0](https://www.npmjs.com/package/enzyme-adapter-react-16.1)
 - [enzyme-adapter-react-15 v1.0.6](https://www.npmjs.com/package/enzyme-adapter-react-15)
 - [enzyme-adapter-react-15.4 v1.0.6](https://www.npmjs.com/package/enzyme-adapter-react-15.4)
 - [enzyme-adapter-react-14 v1.0.6](https://www.npmjs.com/package/enzyme-adapter-react-14)
 - [enzyme-adapter-react-13 v1.0.4](https://www.npmjs.com/package/enzyme-adapter-react-13)
 - [enzyme-adapter-utils v1.5.0](https://www.npmjs.com/package/enzyme-adapter-utils)

**Pull request merged**
