### PR TITLE
Remove broken link

### PR DESCRIPTION
**Pull request by kmkr**

### CODE REVIEW

**Comment by ljharb** [comment]
I don't think this link is meant to be broken. We should probably fix it instead of removing it.

**Comment by lelandrichardson** [comment]
Actually, this fix is correct. I was going to do a jasmine guide, but there's not really anything specific for jasmine that needs to be done. It's more the bundlers + environments that are the issue.

**Comment by ljharb** [comment]
Seems like it'd still be useful to have a guide there that says "nothing needs to be done!" so Jasmine users don't think their tool is omitted.

**Comment by lelandrichardson** [comment]
@ljharb fair enough. PRs welcome :)

I think there are a couple of the `enzyme-example-*` projects that are using jasmine already. we could potentially rename them to include jasmine in the name... although the names of these projects are going to get a bit crazy :)

**Pull request merged**
