### PR TITLE
Calling `props()` after a state change should be updated to `find()`

### PR DESCRIPTION
**Pull request by peter-mouland**
This PR has come about from this issue: https://github.com/airbnb/enzyme/issues/1299

If I have misunderstood anything please let me know.

Thanks

### CODE REVIEW

**Comment by bregenspan** [comment]
As far as I understand it, this is a side effect of https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md#element-referential-identity-is-no-longer-preserved, so maybe it makes sense to put this as a sub-head under that?

**Comment by ljharb** [comment]
@peter-mouland any interest in updating this PR?

**Comment by peter-mouland** [comment]
hey, yeah - can do, do you have any stats on how many people look at the migrate docs now?

**Comment by ljharb** [comment]
I'm afraid github doesn't offer any of those stats :-/ but i did get a bug or three filed about its content in the last 6 months, so it's not nobody!

**Comment by peter-mouland** [comment]
cool - consider it updated.  I've also updated the example to make it more consistent / readable (it was a while ago i wrote this up, old code never looks good 🤦‍♂️ !!)

**Pull request merged**
