### PR TITLE
clarify alternative to wrapper.setState()

### PR DESCRIPTION
**Pull request by RebootJeff**

### CODE REVIEW

**Comment by ljharb** [comment]
LGTM

**Comment by Aweary** [comment]
@RebootJeff can you update your PR with the latest changes from master? We can merge after that!

**Comment by RebootJeff** [comment]
@Aweary I used GitHub's "Update Branch" feature (new to me), which seems to have merged `master` into my `patch-1` branch. Let me know if you prefer a rebase instead.

**Comment by Aweary** [comment]
Looks good @RebootJeff thanks!

**Comment by ljharb** [comment]
In the future, a rebase is preferred. Merge commits make `git bisect` cry.

**Comment by Aweary** [comment]
@ljharb I squashed the commits before merging, is that still a problem?

**Comment by ljharb** [comment]
@Aweary ah ok, that's better then, altho i dislike the squash feature too :-/ what I'd really like is for github to show a button to PR authors for "rebase on top of master", and for admins to be able to check a box to disallow merge commits, thus requiring PR authors to click that button / rebase before things are merged.

**Comment by Aweary** [comment]
@ljharb got it. So for future reference, contributors should ask PR authors to rebase if there are any merge commits, then *don't* use the squash option when merging the PR. Does that sound right? I want to be sure we're all on the same page as far as commit/merge policies go.

**Comment by ljharb** [comment]
Yes, ideally. Obviously tho it's unreasonable to ask every contributor to rebase every time, especially when the PR is documentation and was made in the web UI, so use your judgement.

Order of my merge preferences:
 1. command-line-merged fast-forward of a rebased PR (no-merge, or otherwise-fast-forwardable merge commit, as appropriate)
 1. "merge button" of an otherwise fast-forwardable rebased PR
 1. "merge button" of a PR (that doesn't have a bunch of sloppy commits nor any merge commits)
 1. "merge + squash button" of a PR that has those things ^

It's also always cool to use your own judgement, none of these things will be a catastrophe either way :-)

**Comment by Aweary** [comment]
Awesome, thanks for clarifying. Saving this comment as a reference 👍

**Comment by Aweary** [comment]
ping @blainekasten @nfcampos, probably good to all be on the same page 😄

**Pull request merged**
