### PR TITLE
Update react test renderer to v16.1.1 for React@16

### PR DESCRIPTION
**Pull request by mabounassif**
This addressed the following issue: https://github.com/airbnb/enzyme/issues/1366

### CODE REVIEW

**Comment by bdwain** [comment]
I don't think this change is necessary. ^16.0.0-0 is satisfied by 16.1.1. The user just needs to say `npm update` or `yarn upgrade` and it should update test renderer for them. No need to change the semver every time they release a patch.

**Comment by ljharb** [comment]
Since this fixes a bug, it might be a good change to make - but does this react-test-renderer work with all versions of react v16?

**Comment by bdwain** [comment]
it does work. they intend to support all of v16 as they update test renderer. the peer dependency on react is only ^16.0.0

**Comment by mabounassif** [comment]
I agree with what has been said above. I should have realized it was a caret - I'm a bit embarrassed :)

Closing this.

**Pull request closed without merging**
