### PR TITLE
Updating the example to import `sinon`

### PR DESCRIPTION
**Pull request by shidhincr**
Just to make sure that `sinon` was properly imported in the example code.

```
it('simulates click events', () => {
    const onButtonClick = sinon.spy();
    const wrapper = shallow(
      <Foo onButtonClick={onButtonClick} />
    );
    wrapper.find('button').simulate('click');
    expect(onButtonClick.calledOnce).to.be.true;
  });
```

### CODE REVIEW

**Comment by simplyianm** [comment]
There's more than just Sinon missing. (e.g., Foo, { expect })

**Comment by lelandrichardson** [comment]
Yah some of these examples are sort of just to give a gist of what's going on but aren't necessarily full examples. I don't think it's a bad idea to make them 100% copy-and-paste-functional though, but we'd have to add a lot more to some of these :/

**Comment by shidhincr** [comment]
@lelandrichardson Agree.. I would vote for to make them 100% copy-and-paste-functional, as most of the times users use the sample code from these examples to try out the library/framework.

**Comment by lelandrichardson** [comment]
I'll go ahead and merge this since the PR to rip out sinon is going to take a little while to merge...

**Pull request merged**
