### PR TITLE
Lock uuid version to 3.0.1

### PR DESCRIPTION
**Pull request by ryanve**
Testing this out in attempt to fix https://github.com/airbnb/enzyme/issues/1020

### CODE REVIEW

**Comment by ryanve** [comment]
I was testing this out on [our fork](https://github.com/plangrid/enzyme). Did not mean to PR here. 

With this change we didn't get the uuid error but instead get this one. 

```
Cannot find module 'enzyme/build/ShallowWrapper' from 'utils.js'
```

**Comment by ljharb** [comment]
On the fork, you may need to manually run the build process, as those files aren't in git.

**Comment by ryanve** [comment]
Right—thanks :)

**Comment by ryanve** [comment]
Ok after that it goes back to giving the original uuid error. So this is not the fix.

**Comment by ljharb** [comment]
can you console.log what `require.resolve('uuid')` is, inside enzyme? I still suspect it's something about your node_modules layout.

**Comment by ryanve** [comment]
`require.resolve('uuid')` is `/Users/me/project/node_modules/uuid/index.js`

`require.resolve('uuid/v4')` is `/Users/me/project/node_modules/uuid/v4.js`

**Comment by ljharb** [comment]
OK, it's using `node_modules/uuid`, not `node_modules/enzyme/node_modules/uuid` - what version  does *that* package.json have in it? I'm going to guess not v3.1.0 - which should mean that `npm ls` should be exiting nonzero.

Perhaps you have a lock file with an invalid dependency graph?

**Comment by ryanve** [comment]
I deleted `node_modules` and `package-lock.json`. I think the graph is ok. Could it relate to the `build` step? [uuid/v4](https://github.com/kelektiv/node-uuid/blob/v3.1.0/v4.js) exports a commonJS module not an ES6 one. [Importing as a member fixes it.](https://github.com/plangrid/enzyme/pull/3/files)

```
import { v4 as uuidv4 } from 'uuid';
```

**Comment by ljharb** [comment]
That's only because `require('uuid').v4` is working for you, which shouldn't be needed in v3.1. iow, `import uuidv4 from 'uuid/v4'` should still be working.

Perhaps your build process is indeed breaking it?

**Pull request closed without merging**
