### PR TITLE
docs: add AVA guide

### PR DESCRIPTION
**Pull request by mikenikles**
This adds an example of how to use enzyme with [AVA](https://github.com/avajs/ava).

### CODE REVIEW

**Comment by ljharb** [comment]
We should probably add tape as well - since ava is basically a runner for tape, should those be the same document, or a different one?

**Comment by mikenikles** [comment]
Given that AVA and tape are so similar, I think keeping both in the same document is ok. I can apply that to this PR.

**Comment by nfcampos** [comment]
tape and ava do have some significant differences but they mostly only appear when testing async code. since most test code using enzyme will be synchronous I think they can be the same guide

**Comment by ljharb** [comment]
@mikenikles would you mind rebasing this, so we can get it in?

**Comment by ljharb** [comment]
@mikenikles Thanks! Any chance you'd mind rebasing locally so as to remove the merge commit?

**Comment by mikenikles** [comment]
I clearly made this worse... I gave rebasing a shot based on some docs, any hint you can give me to do that properly?

**Comment by mikenikles** [comment]
Looks better... I hope :)

**Comment by ljharb** [comment]
Thanks!

**Pull request merged**
