### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by annie-annie**
change method call from `to.equal` to `toEqual`

### CODE REVIEW

**Comment by ljharb** [comment]
Indeed, all our docs use chai syntax, so this is correct as is.

**Comment by scott-ln** [comment]
Okay, but that's not made clear anywhere, which is why you've had multiple PRs from people on this topic. It's hostile to learners. Could you please consider improving your documentation to highlight that fact on individual documentation pages?

**Comment by ljharb** [comment]
It would be hostile to learners in the same way to use jest matcher syntax.

we could import expect from chai in all our examples, i suppose.

**Comment by scott-ln** [comment]
Yes of course, I'm not suggesting that you switch to the other syntax, just asking that you make it clear which syntax you're using. Thank you.

**Pull request closed without merging**
