### PR TITLE
Documentation, Alphabetize API Reference function links in Table of Contents

### PR DESCRIPTION
**Pull request by staticinstance**
Makes it easier to scan for functions

### CODE REVIEW

**Comment by lelandrichardson** [comment]
Seems reasonable. I was originally trying to group them semantically, but the order in that case is not always very clear. This may be more obvious.

@ljharb do you have any thoughts?

**Comment by ljharb** [comment]
I tend to prefer semantically, because people will use find-in-page to find what they want. Alphabetically seems fine too though, and less subjective.

**Comment by lencioni** [comment]
I generally prefer alphabetical because it is a simple rule that is easy for producers and consumers to follow.

**Comment by ljharb** [comment]
@staticinstance would you mind squashing these 3 commits to one?

**Comment by ljharb** [comment]
@staticinstance that added merge commits rather than being rebased down to a single commit :-/

**Comment by staticinstance** [comment]
Thanks, I'll work on fixing that.

**Comment by staticinstance** [comment]
It should be fixed now.

**Comment by lelandrichardson** [comment]
Thanks, @staticinstance !

**Comment by staticinstance** [comment]
Thanks for merging :+1:

**Pull request merged**
