### PR TITLE
[enzyme-adapter-react-{16,16.3}] [fix] `forwardRef`: respect `.displayName`

### LINKED ISSUE #1810: displayName set on forwardRef is not honored
**Describe the bug**
In styled-components v4 beta we started decorating the forwardRef wrapper with displayName and various other statics to reduce the amount of interim component layers during rendering and preserve various library behaviors. https://github.com/styled-components/styled-components/blob/30c372cf635e0db77f74c0aaacf60deda729581c/src/models/StyledComponent.js#L249-L311

However, it doesn't seem like enzyme surfaces a `displayName` set on a forwardRef component.

**To Reproduce**
See this codesandbox: https://codesandbox.io/s/yv7l2p76q9

**Expected behavior**
The test expectations should work since name and displayName are set on the forwardRef node.

It would be really great if this could work for a few reasons:

1. Shallow rendering does not currently render the immediate child of ForwardRef, so if we modified our library so the wrapped child of ForwardRef had all the statics etc it still wouldn't work without diving

2. The components don't show up at all when using "find" off of "mount" since ForwardRef isn't honoring displayName

Sidebar: I really wish ref forwarding was implemented as a decorator or class mixin... _sigh_.

### PR DESCRIPTION
**Pull request by ljharb**
Fixes #1810.

### CODE REVIEW

**Comment by ljharb** [comment]
@jgzuke because the 16 adapter is for 16.0 - 16.5, but the 16.3 adapter is only for 16.3, and those special cases are only in 16.3+.

**Comment by ljharb** [comment]
I don't think it's really worth it; the original issue's repro requires styled-components, but in general, if it shows up in `.debug()`, it's findable.

**Comment by probablyup** [comment]
Thanks Jordan!

**Comment by darkowic** [comment]
Hello there! Will it be released anytime soon?

**Pull request merged**
