### PR TITLE
Add Discord logo and link to testing channel

### PR DESCRIPTION
**Pull request by Aweary**
This will let users who are looking for support know they can go to #testing in reactiflux for help, instead of just opening an issue first :)

### CODE REVIEW

**Comment by Aweary** [comment]
@ljharb @lelandrichardson is this cool with you guys?

**Comment by ljharb** [comment]
I really don't like discord, which is why i'm not in Reactiflux anymore. Adding it to the readme means that all contributors are somewhat obligated to provide support there. (gitter is fine because it has an irc bridge)

**Comment by Aweary** [comment]
Discord isn't the best but Reactiflux does seem to be the most active online source for React-related projects. I personally have no problem hanging out in #testing (I already do) but I'll defer to the other contributors. I don't want to set any expectations for anyone else.

**Comment by Aweary** [comment]
@nfcampos @blainekasten what do you guys think?

**Comment by nfcampos** [comment]
I'm not a big fan of discord but if the others want it I'm fine with it

**Comment by blainekasten** [comment]
Also not a big fan of discord. I jump in there every once in a while. But I frankly don't have enough time to sit in reactiflux that often unfortunately.. I don't know that this means we can't have it in the README though. There are a lot of people using enzyme now. And a lot of them sit in reactiflux. So even if a new person comes in to use enzyme and jumps in discord, I'm sure they will receive some help.

**Comment by Aweary** [comment]
> I don't know that this means we can't have it in the README though. There are a lot of people using enzyme now. And a lot of them sit in reactiflux. So even if a new person comes in to use enzyme and jumps in discord, I'm sure they will receive some help.

I agree with this, I don't personally assume that being directed to a community chat would imply that we the maintainers are guaranteeing support there. I know I personally watch it, but I was just thinking that since it is an active community, it's a great resource for our users.

**Comment by ljharb** [comment]
I don't mind listing it as long as it's clear that there's no guarantee of official support there.

**Comment by Aweary** [comment]
LGTM, I'll personally watch the channel and see if there's any confusion about it. If there is, we can remove it.

**Comment by Aweary** [comment]
LGTM

**Comment by Aweary** [comment]
I guess I can't approve my own PR? 😄

**Pull request merged**
